#!/bin/sh

if [ "$#" != 2 ]; then 
	echo "Niepoprawna ilosc argumentow wejsciowych"
	exit 1
fi

if [ ! -d $1 ] || [ ! -d $2 ]; then 
	echo "Nie znaleziono katalogu"
	exit 2
fi

for file in `ls -a  $1`; do	
	if [ ! -d $1/$file ]; then
		if [ -e $2/$file ] && [ ! -d $2/$file ]; then
		rm -rf $1/$file	  
		fi
	fi
done
